entrypoint: ./bin/rails server
env: flex
runtime: ruby
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 5

env_variables:
  SECRET_KEY_BASE: [SECRET_KEY_BASE]

beta_settings:
  cloud_sql_instances: [prismatic-smoke-408205:us-central1:myrailsblog-db]